baseURL: https://www.rightcmms.com/
languageCode: en-us
theme: hugo-fresh
summaryLength: 21

params:
  sidebar:
  #   #logo from /images/logos/____.svg
  #   logo: fresh
  # - sections:
  #     title: Title 1
  #     icon: cat
  #   - links:
  #       url: /landing/
  #       text: landing
  #   - links:
  #       url: /landing/
  #       text: landing
  # - sections:
  #     title: Title 1
  #     icon: cat
  #   - links:
  #       url: /landing/
  #       text: landing
  #   - links:
  #       url: /landing/
  #       text: landing
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/CMMS-rightcmms-full-logo.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600,700]
    # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Downloads
    url: /landing
  - title: Blog
    url: /blog
  - title: Learn
    sublinks:
    - title: Preventive Maintenance
      url: /preventive-maintenance
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
  - title: Sign up
    url: /
  - title: Login
    url: /
    button: true
  #Navbar for landing pages without any menu
  empty_navbar:
  #Landing Page
  landing:
    image: ebook
    alt: CMMS Download the ultimate guide on Preventive Maintenance ebook image
    title: Download the ultimate guide on Preventive Maintenance
    subtitle:
    contenttitle: By reading this ebook you will understand
    text:
    ul:
    - li: Why preventive maintenance?
    - li: What is preventive maintenance? 
    - li: How is a program maintenance program developed?
    - li: When is the right time to implement a PM program?
    - li: What could go wrong with a PM program?
  thankyou:
    title: Thank You. You hungry learner :)
    subtitle: To download the eBook, please check youur email.
    buttons:
    - buttonText: Home
      buttonLink: /
    - buttonText: Show me more resources
      buttonLink: /resources
  hero:
    # Main hero title
    title: Know everything CMMS, then BUY.
    # Hero subtitle (optional)
    subtitle: Right CMMS will handhold you in your CMMS buying journey
    # Button text
    buttontext: 
    # Where the main hero button links to
    buttonlink: ""
    # Hero image (from static/images/___)
    image: illustrations/CMMS-Homepage-Banner-image.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  section1:
    title: The Top CMMS Vendors
    subtitle: Know everything about them
    tiles:
    - title: SALES PROCESS
      icon: mouse-globe
      text: Why CMMS? What is a CMMS? How it helps? Everything you wanted to know about a CMMS and did not know who to ask. Learn through a number of useful articles that will support you in beginning your CMMS journey.
      url: /
      buttonText: 
    - title: USER RATINGS
      icon: laptop-cloud
      text: Are you ready for a CMMS yet? Would it be ok to start with a spreadsheet system? If I opt for a CMMS, what ROI can I expect? How does the implementation progress? What kind of resources does a business have to commit when implementing a CMMS?
      url: /
      buttonText: 
    - title: PRICING
      icon: plug-cloud
      text: Which CMMS to buy? Who are the vendors? Who can best meet my requirements? How do they compare amongst each other? There are so many out there. Are there FREE trials that can help me test drive the right CMMS?
      url: /
      buttonText: 
  section2:
    title: The Right CMMS Promise
    subtitle: This is how we help
    image: CMMS-The-right-cmms-promise-Mockup-image.png
    lazyimage: CMMS-The-right-cmms-promise-Mockup-image-lazy.png
    alt: CMMS The right cmms promise Mockup image
    features:
      # Icon (from /images/illustrations/icons/___.svg)
    - title: LEARN
      text: Why CMMS? What is a CMMS? How it helps? Everything you wanted to know about a CMMS and did not know who to ask. Learn through a number of useful articles that will support you in beginning your CMMS journey.
      icon: CMMS-The-right-CMMS-Promise-Learn-Logo
    - title: UNDERSTAND
      text: Are you ready for a CMMS yet? Would it be ok to start with a spreadsheet system? If I opt for a CMMS, what ROI can I expect? How does the implementation progress? What kind of resources does a business have to commit when implementing a CMMS?
      icon: CMMS-The-right-CMMS-Promise-Understand-Logo
    - title: BUY
      text: Which CMMS to buy? Who are the vendors? Who can best meet my requirements? How do they compare amongst each other? There are so many out there. Are there FREE trials that can help me test drive the right CMMS?
      icon: CMMS-The-right-CMMS-Promise-Buy-Logo
  section3:
    title: The CMMS Master Guide
    subtitle: Crunch the numbers, impress your management
    image: illustrations/mockups/app-mockup.png
    lazyimage: illustrations/mockups/app-mockup-lazy.png
    alt: CMMS The master CMMS Guide Mockup image
    buttonText: Download
    buttonLink: "#"
  section4:
    title: CMMS University
    subtitle: Learn to your heartâ€™s content
    clients:
    - name: Blog 1
      text: Why CMMS? What is a CMMS? How it helps? Everything you wanted to know about a CMMS and did not know who to ask. Learn through a number of useful articles that will support you in beginning your CMMS journey.
      img: 1
      buttonText: Read More
      buttonLink: 
    - name: Blog 2
      text: Are you ready for a CMMS yet? Would it be ok to start with a spreadsheet system? If I opt for a CMMS, what ROI can I expect? How does the implementation progress? What kind of resources does a business have to commit when implementing a CMMS?
      img: 2
      buttonText: Read More
      buttonLink: 
    - name: Blog 3
      text: Which CMMS to buy? Who are the vendors? Who can best meet my requirements? How do they compare amongst each other? There are so many out there. Are there FREE trials that can help me test drive the right CMMS?
      img: 3
      buttonText: Read More
      buttonLink: 
    ebooks:
    - title: The most kick ass ebook on CMMS
      buttonText: Download
      img: 1
      buttonLink: 
    - title: The second most kick ass ebook on CMMS
      buttonText: Download
      img: 2
      buttonLink: 
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: CMMS-rightcmms-full-white-logo.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: First Blog
          link: /blog/first
        - text: Second Blog
          link: /blog/second
        - text: Third Blog
          link: /blog/third
        - text: Fourth Blog
          link: /blog/fourth
